version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - printenv
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region us-east-1 s3 sync ./dist/ s3://silvara-makerlab-code-bucket/ --acl=public-read --delete
